package hibernate.pojo;
// Generated Jun 13, 2015 12:19:47 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * SContest generated by hbm2java
 */
public class SContest  implements java.io.Serializable {


     private String SPhotoId;
     private SUsers SUsers;
     private BigDecimal SVotes;
     private String SPhoto;

    public SContest() {
    }

	
    public SContest(String SPhotoId, SUsers SUsers, String SPhoto) {
        this.SPhotoId = SPhotoId;
        this.SUsers = SUsers;
        this.SPhoto = SPhoto;
    }
    public SContest(String SPhotoId, SUsers SUsers, BigDecimal SVotes, String SPhoto) {
       this.SPhotoId = SPhotoId;
       this.SUsers = SUsers;
       this.SVotes = SVotes;
       this.SPhoto = SPhoto;
    }
   
    public String getSPhotoId() {
        return this.SPhotoId;
    }
    
    public void setSPhotoId(String SPhotoId) {
        this.SPhotoId = SPhotoId;
    }
    public SUsers getSUsers() {
        return this.SUsers;
    }
    
    public void setSUsers(SUsers SUsers) {
        this.SUsers = SUsers;
    }
    public BigDecimal getSVotes() {
        return this.SVotes;
    }
    
    public void setSVotes(BigDecimal SVotes) {
        this.SVotes = SVotes;
    }
    public String getSPhoto() {
        return this.SPhoto;
    }
    
    public void setSPhoto(String SPhoto) {
        this.SPhoto = SPhoto;
    }




}


