package hibernate.pojo;
// Generated Jun 13, 2015 12:19:47 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SUsers generated by hbm2java
 */
public class SUsers  implements java.io.Serializable {


     private String SHandle;
     private String SEmail;
     private String SFirstName;
     private String SLastName;
     private String SSex;
     private String SCollege;
     private Set<SContest> SContests = new HashSet<SContest>(0);
     private Set<SHallOfFame> SHallOfFames = new HashSet<SHallOfFame>(0);

    public SUsers() {
    }

	
    public SUsers(String SHandle, String SEmail, String SFirstName, String SLastName, String SSex) {
        this.SHandle = SHandle;
        this.SEmail = SEmail;
        this.SFirstName = SFirstName;
        this.SLastName = SLastName;
        this.SSex = SSex;
    }
    public SUsers(String SHandle, String SEmail, String SFirstName, String SLastName, String SSex, String SCollege, Set<SContest> SContests, Set<SHallOfFame> SHallOfFames) {
       this.SHandle = SHandle;
       this.SEmail = SEmail;
       this.SFirstName = SFirstName;
       this.SLastName = SLastName;
       this.SSex = SSex;
       this.SCollege = SCollege;
       this.SContests = SContests;
       this.SHallOfFames = SHallOfFames;
    }
   
    public String getSHandle() {
        return this.SHandle;
    }
    
    public void setSHandle(String SHandle) {
        this.SHandle = SHandle;
    }
    public String getSEmail() {
        return this.SEmail;
    }
    
    public void setSEmail(String SEmail) {
        this.SEmail = SEmail;
    }
    public String getSFirstName() {
        return this.SFirstName;
    }
    
    public void setSFirstName(String SFirstName) {
        this.SFirstName = SFirstName;
    }
    public String getSLastName() {
        return this.SLastName;
    }
    
    public void setSLastName(String SLastName) {
        this.SLastName = SLastName;
    }
    public String getSSex() {
        return this.SSex;
    }
    
    public void setSSex(String SSex) {
        this.SSex = SSex;
    }
    public String getSCollege() {
        return this.SCollege;
    }
    
    public void setSCollege(String SCollege) {
        this.SCollege = SCollege;
    }
    public Set<SContest> getSContests() {
        return this.SContests;
    }
    
    public void setSContests(Set<SContest> SContests) {
        this.SContests = SContests;
    }
    public Set<SHallOfFame> getSHallOfFames() {
        return this.SHallOfFames;
    }
    
    public void setSHallOfFames(Set<SHallOfFame> SHallOfFames) {
        this.SHallOfFames = SHallOfFames;
    }




}


