package hibernate.pojo;
// Generated Jun 13, 2015 12:19:47 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * SVoteRestrict generated by hbm2java
 */
public class SVoteRestrict  implements java.io.Serializable {


     private BigDecimal SId;
     private String SVoter;
     private String SVotee;
     private Boolean SVoteFlag;

    public SVoteRestrict() {
    }

	
    public SVoteRestrict(BigDecimal SId, String SVoter, String SVotee) {
        this.SId = SId;
        this.SVoter = SVoter;
        this.SVotee = SVotee;
    }
    public SVoteRestrict(BigDecimal SId, String SVoter, String SVotee, Boolean SVoteFlag) {
       this.SId = SId;
       this.SVoter = SVoter;
       this.SVotee = SVotee;
       this.SVoteFlag = SVoteFlag;
    }
   
    public BigDecimal getSId() {
        return this.SId;
    }
    
    public void setSId(BigDecimal SId) {
        this.SId = SId;
    }
    public String getSVoter() {
        return this.SVoter;
    }
    
    public void setSVoter(String SVoter) {
        this.SVoter = SVoter;
    }
    public String getSVotee() {
        return this.SVotee;
    }
    
    public void setSVotee(String SVotee) {
        this.SVotee = SVotee;
    }
    public Boolean getSVoteFlag() {
        return this.SVoteFlag;
    }
    
    public void setSVoteFlag(Boolean SVoteFlag) {
        this.SVoteFlag = SVoteFlag;
    }




}


